"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 14:13:53.954787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appsetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('canonicalproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('ean', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('quantity_value', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True),
    sa.Column('quantity_unit', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('search_text', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean')
    )
    op.create_table('chain',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collectorrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('products_checked', sa.Integer(), nullable=False),
    sa.Column('prices_changed', sa.Integer(), nullable=False),
    sa.Column('new_listings', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_messages', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loginattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loginattempt_attempted_at'), 'loginattempt', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_loginattempt_ip'), 'loginattempt', ['ip'], unique=False)
    op.create_table('product',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('chain_id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('chain_product_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('canonical_product_id', sa.Integer(), nullable=True),
    sa.Column('link_source', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('ean', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('size_text', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('quantity_value', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True),
    sa.Column('quantity_unit', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('search_text', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('first_seen_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonicalproduct.id'], ),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'chain_id', 'chain_product_id', 'postal_code')
    )
    op.create_index(op.f('ix_listing_canonical_product_id'), 'listing', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_listing_chain_id'), 'listing', ['chain_id'], unique=False)
    op.create_index(op.f('ix_listing_ean'), 'listing', ['ean'], unique=False)
    op.create_index(op.f('ix_listing_last_seen_at'), 'listing', ['last_seen_at'], unique=False)
    op.create_table('shoppinglistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonicalproduct.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_product_id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('rules_key', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('chain_id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_store_name_lower', 'store', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('listingprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listingprice_listing_last_seen', 'listingprice', ['listing_id', 'last_seen_at'], unique=False)
    op.create_table('productmatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_product_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['canonicalproduct.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_product_id', 'listing_id')
    )
    op.create_index(op.f('ix_productmatch_canonical_product_id'), 'productmatch', ['canonical_product_id'], unique=False)
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('closed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_started_at'), 'trip', ['started_at'], unique=False)
    op.create_index(op.f('ix_trip_store_id'), 'trip', ['store_id'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('product_key', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3, asdecimal=False), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_created_at'), 'purchase', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_product_key'), 'purchase', ['product_key'], unique=False)
    op.create_index(op.f('ix_purchase_trip_id'), 'purchase', ['trip_id'], unique=False)
    # ### end Alembic commands ###

    # Seed data (hard-coded so this migration never changes when app code does).
    chain = sa.table("chain", sa.column("id", sa.String), sa.column("name", sa.String))
    op.bulk_insert(chain, [{"id": cid, "name": name} for cid, name in CHAINS])
    store = sa.table("store", sa.column("name", sa.String), sa.column("chain_id", sa.String))
    op.bulk_insert(store, [{"name": name, "chain_id": cid} for cid, name in CHAINS])
    setting = sa.table("appsetting", sa.column("key", sa.String), sa.column("value", sa.String))
    op.bulk_insert(setting, [{"key": "postal_code", "value": "28020"}])


CHAINS = [
    ("mercadona", "Mercadona"),
    ("carrefour", "Carrefour"),
    ("lidl", "Lidl"),
    ("dia", "Dia"),
    ("alcampo", "Alcampo"),
    ("aldi", "Aldi"),
    ("eroski", "Eroski"),
    ("consum", "Consum"),
    ("ahorramas", "Ahorramas"),
    ("el-corte-ingles", "El Corte Inglés"),
]


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_trip_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_product_key'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_created_at'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_trip_store_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_started_at'), table_name='trip')
    op.drop_table('trip')
    op.drop_index(op.f('ix_productmatch_canonical_product_id'), table_name='productmatch')
    op.drop_table('productmatch')
    op.drop_index('ix_listingprice_listing_last_seen', table_name='listingprice')
    op.drop_table('listingprice')
    op.drop_index('uq_store_name_lower', table_name='store')
    op.drop_table('store')
    op.drop_table('shoppinglistitem')
    op.drop_index(op.f('ix_listing_last_seen_at'), table_name='listing')
    op.drop_index(op.f('ix_listing_ean'), table_name='listing')
    op.drop_index(op.f('ix_listing_chain_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_canonical_product_id'), table_name='listing')
    op.drop_table('listing')
    op.drop_table('product')
    op.drop_index(op.f('ix_loginattempt_ip'), table_name='loginattempt')
    op.drop_index(op.f('ix_loginattempt_attempted_at'), table_name='loginattempt')
    op.drop_table('loginattempt')
    op.drop_table('collectorrun')
    op.drop_table('chain')
    op.drop_table('canonicalproduct')
    op.drop_table('appsetting')
    # ### end Alembic commands ###
