"""product type

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 16:18:54.216098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonicalproduct', sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True))
    op.create_index(op.f('ix_canonicalproduct_product_type'), 'canonicalproduct', ['product_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonicalproduct_product_type'), table_name='canonicalproduct')
    op.drop_column('canonicalproduct', 'product_type')
    # ### end Alembic commands ###
